  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Background"
  identifier = "background"
  weight = 200
  url = "/background/"

  #To be added
  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "Activities"
  weight = 400
  identifier = "activities"

  [[main]]
  name = "Talks"
  weight = 410
  identifier = "talks"
  url = "/talks/"
  parent = "activities" 

  [[main]]
  name = "Publications"
  weight = 420
  identifier = "publications"
  url = "/publications/"
  parent = "activities" 
  
  # To be added
  #[[main]]
  #name = "Awards"
  #weight = 430
  #identifier = "awards"
  #url = "/awards/"
  #parent = "activities"  

  [[main]]
  name = "About"
  weight = 500
  identifier = "about"
  url = "/about/"

  # [[main]]
  # name = "Contact"
  # weight = 600
  # identifier = "contact"
  # url = "/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"