#baseURL = "https://example.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Konstantin Tkachuk"



# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule
theme = "anatole"

#[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  #[[module.imports]]
  #  path = "github.com/lxndrblz/anatole"
  #  disable = false


summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[params]
title = "I'm Konstantin Tkachuk"
author = "Konstantin Tkachuk"
description = """Schwarzman Scholar ‘23 | COO at Future International Foundation, Inc. 
Startup Advisor | Web3 & Blockchain research 
Aspiring Technology Policy researcher"""
profilePicture = "images/Me.png"